### ISSUE TITLE
plot function

### ISSUE THREAD

**Issue by sapphire75710** [helske/seqHMM#10]
Hi there,

A question about how the plot function is developed. I have a markov chain object (known initial probability, known emission probability and known transition matrix) and can I use the plot function in your package without fitting the hmm model?

**Comment by satuhelske** [comment]
Hi,

you can construct the model with the `build_hmm` function. It creates an object of class `hmm`, for which we have defined a plotting method. The fitting function merely estimates the model parameters, so there is no need to use `fit_model` if you already know your parameters.

**Comment by sapphire75710** [comment]
Thanks a lot!

**Comment by satuhelske** [comment]
You're welcome.
