### ISSUE TITLE
Computing sequence (log)-likelihood

### ISSUE THREAD

**Issue by lordbitin** [helske/seqHMM#16]
Hi,

I am not sure of how to compute the (log)-likelihood of a test sequence for a fitted model in this package, i.e, given a sequence _o_ and a model _H_, calculate _log[P(o|H)]_

Is there a function to directly compute this? I have coded this (horrible) workaround, changing temporaly some of the model parameters and calling the package _logLik_ function:

```{r}
sequenceLikelihood <- function (hmm,seq) {
  aux <- hmm
  aux$observations <- seq
  aux$n_sequences <- 1
  if (!is.data.frame(seq)) {
    aux$length_of_sequences <- ncol(seq[[1]])
  } else {
    aux$length_of_sequences <- ncol(seq)
  }
  
  result <- seqHMM:::logLik.hmm(aux)
  
  if (is.nan(result)) -Inf
  else result
}
```

Is there any built-in function to do this better?

Thanks!

**Comment by helske** [comment]
Do you mean that you have estimated your model with using one sequence, and you then want to test the model using another sequence? If so, you need to build your own function for that as you have done. Note that there is no need to make a new object ``aux``, you can modify the `hmm` object inside the function without altering the `hmm` in the calling environment. And you can just use `logLik(hmm)` instead  of `seqHMM:::logLik` unless you wan't some miniscule performance boost by calling the correct method directly.

**Comment by lordbitin** [comment]
Thanks!
