### ISSUE TITLE
Problem installing the package

### ISSUE THREAD

**Issue by rajeshbawa** [helske/seqHMM#19]
Guys, I am having an issue installing the package. It keeps throwing this error at me. Could please help me out here. Thanks.

icpc -I/opt/apps/intel13_1/R/3.2.2/lib64/R/include -DNDEBUG  -I/usr/local/include -I"/home/rajesh13/R/x86_64-pc-linux-gnu-library/3.2/Rcpp/include" -I"/home/rajesh13/R/x86_64-pc-linux-gnu-library/3.2/RcppArmadillo/include"  -fopenmp -fpic  -g -O2  -c viterbi.cpp -o viterbi.o
/home/rajesh13/R/x86_64-pc-linux-gnu-library/3.2/Rcpp/include/Rcpp/algorithm.h(153): warning #858: type qualifier on return type is meaningless
          static inline RCPP_CONSTEXPR double ZERO() { return 0.0; }
                        ^

/home/rajesh13/R/x86_64-pc-linux-gnu-library/3.2/Rcpp/include/Rcpp/algorithm.h(154): warning #858: type qualifier on return type is meaningless
          static inline RCPP_CONSTEXPR double ONE() { return 1.0; }
                        ^

/home/rajesh13/R/x86_64-pc-linux-gnu-library/3.2/Rcpp/include/Rcpp/algorithm.h(162): warning #858: type qualifier on return type is meaningless
          static inline RCPP_CONSTEXPR int ZERO() { return 0; }
                        ^

/home/rajesh13/R/x86_64-pc-linux-gnu-library/3.2/Rcpp/include/Rcpp/algorithm.h(163): warning #858: type qualifier on return type is meaningless
          static inline RCPP_CONSTEXPR int ONE() { return 1; }
                        ^

viterbi.cpp(40): error #140: too many arguments in function call
      delta.col(obs.n_cols - 1).max(q(k, obs.n_cols - 1));
                                    ^

compilation aborted for viterbi.cpp (code 2)
make: *** [viterbi.o] Error 2
ERROR: compilation failed for package ‘seqHMM’
* removing ‘/home/rajesh13/R/x86_64-pc-linux-gnu-library/3.2/seqHMM’

The downloaded source packages are in
	‘/tmp/RtmpWmMkcT/downloaded_packages’
Warning message:
In install.packages("seqHMM") :
  installation of package ‘seqHMM’ had non-zero exit status

**Comment by helske** [comment]
This is due to recent changes in Armadillo, and is now corrected in 38af624735848f15b4f2f46d3a561e9baf464c32.

**Comment by rajeshbawa** [comment]
Thanks, this fixed the issue.
