### ISSUE TITLE
Error in build_hmm

### ISSUE THREAD

**Issue by gunjanthesystem** [helske/seqHMM#22]
Hi,

I was trying to implement single channel hmm following the reference manual. I get the error <code>"Error in build_hmm(observations = mvad_seq, n_states = 4) : unused argument (n_states = 4)"</code> when i try to build hmm with given states. The code i used:

```
data("mvad", package = "TraMineR")
mvad_alphabet <- c("employment", "FE", "HE", "joblessness", "school","training")
mvad_labels <- c("employment", "further education", "higher education","joblessness", "school", "training")
mvad_scodes <- c("EM", "FE", "HE", "JL", "SC", "TR")
mvad_seq <- seqdef(mvad, 17:86, alphabet = mvad_alphabet, states = mvad_scodes, labels = mvad_labels, xtstep = 6)
init_hmm_mvad1 <- build_hmm(observations = mvad_seq, n_states = 4)
```

Kindly suggest.

Thanks a million,

**Comment by satuhelske** [comment]
Hi,

at first, please check that you are using the latest version of seqHMM (1.0.7). If that does not help, can you show the `sessionInfo()`?

**Comment by gunjanthesystem** [comment]
Thanks @satuhelske, apologies , turned out my installed version was 1.0.5. The 1.0.7 version seems to be working fine. If it is not asking too much, could you give pointers on how to predict the next value in the sequence using seqHMM.

Thanks,
gunjanthesystem

**Comment by NicolasMontes** [comment]
Hi,
i am new in HMM, i readed the paper Hidden Markov Model Induction by Bayesian Model Mergin, by Andreas Stolcke and Stephen Omohundro, in his description talk about the initial model can be gradually transformed into the generating model by repeatedly merging states, they construct a sequence of models obtained by merging samples {ab,abab} , and pik the model with more maximum a posteriori probability.

how do i get all the potential models in R?

thanks
