### ISSUE TITLE
Fit MHMM with Clusters of different rows

### ISSUE THREAD

**Issue by xlko** [helske/seqHMM#24]
Hi,

In the R-documentation example of "build_mhmm" you
are fitting a model with the seqdef-object
"marr_seq" , "child_seq" , "left_seq" all three
seqdef-objects have the same nrow.

Now I'm trying to fit a MHMM with my life-course data.
In my previous analysis I have done an hierarchical clustering.
The classification of the clustering suggests a 5-cluster solution.
The problem is that this 5-cluster has a different number of observations.

So if I build the MHMM, I get following error:
"The number of subjects (rows) is not the same in all channels"
If I cut my list of oberservations to the same number of nrow
the "build_mhmm" function works.

Is there any possibility to model a MHMM with a different number
of rows in the cluster according to my classification?

Thank you and best regards

**Comment by satuhelske** [comment]
Hi xlko,

Yes, clusters can be of varying sizes (different numbers of subjects). I'm assuming there is some confusion with the terminology here. The example you are referring to is for multichannel sequence data meaning that for each subject we have multiple parallel sequences; in the example we have three-channel data with information on marriage, parenthood, and residence annually for each individual.

I'm assuming you have "single-channel" data, i.e., one sequence per subject. The data you give to the observations argument should be an stslist object of the form N x T where N is the number of subjects and T the the length of the sequence (typically the number of time points). If you have multichannel data you have a list of stslists where each list element corresponds to one channel.

I urge you to read the seqHMM vignette which explains the terminology in more detail and shows some examples. See also the help file of the build_hmm function which starts with an example to estimating an HMM to single-channel data.
