### ISSUE TITLE
Mistake in the documentation - code example

### ISSUE THREAD

**Issue by BenHeadikt** [helske/seqHMM#26]
Hello,

I found a mistake in the code examples of your documentation that makes the code stop working.

Your example: 
```
EM + 50 restarts with random starting values for emission probabilities
hmm2 <- fit_model(bhmm, 
  control_em = list(restart = list(times = 50, transition = FALSE, emission = TRUE))
```

The final closing bracket is missing. You might want to correct that.
Besides that, nice package and good documentation!

**Comment by helske** [comment]
Thanks!
