### ISSUE TITLE
ssplot comes out black

### ISSUE THREAD

**Issue by liatmarc** [helske/seqHMM#28]
I have 50,000 sequences (one channel) with 18 states. I subset to a random sample of 2000 to reduce the dimensionality. To plot I tried to just view the first 20 columns. The plot is black but the legend on the right is OK.
attr(myseq,"cpal") <-colorpalette[[18]]
ssplot(myseq,xtlab1:20,legend.prop=0.4)

Thanks for your help

**Comment by satuhelske** [comment]
This is probably because of the number of data points is large compared to the size of the plots. Try adjusting the `border` and `space` arguments. See the `TraMineR::seqplot` function for more information.

**Comment by liatmarc** [comment]
Using border=NA and space = 0, the plot is now visible. Thanks.
