### ISSUE TITLE
How to fix a model with warning: in fit_model, backward probabilities contain non-finite values,NLOPT_FAILURE

### ISSUE THREAD

**Issue by liatmarc** [helske/seqHMM#29]
I have a single channel sequence. I built an HMM based on assumed 4 states, using arbitrary initial values, transition probabilities, emission probabilities. I fit the model using global_step=TRUE, local_step=TRUE.
The EM algorithm failed. The local optimization terminated. Is there a way to adjust the parameters to avoid the warning? Note that I was able to plot and print the hmm (maybe incorrect because of the warning?? ) 
Thanks for your help

**Comment by helske** [comment]
It is hard to know what could be the reason for your problems without actually seeing some sort of reproducible example. What does logLik(your_model) return?

**Comment by liatmarc** [comment]
logLik(my_model) = -2313121 (df = 77).

**Comment by helske** [comment]
As it is not NaN or Inf the model is likely structurally ok, but I can't say much more without seeing the specific model and the error message.

**Comment by helske** [comment]
Closed as old and impossible to figure out the potential issue without reproducible example.
