### ISSUE TITLE
Seed-dependent model fitting success for LCM

### ISSUE THREAD

**Issue by steipatr** [helske/seqHMM#30]
Hi,
I am trying to cluster model-generated time series with seqHMM. I am importing a dataframe of continuous time series, discretizing it, and then running build_lcm and fit_model to get the clusters. For some random seeds, the fitting is successful, for others, it generates (a variety of) error messages. Log likelihood test indicates model is functional (and indeed for some seeds it runs fine). If you could review this and consider the attached files (R script and data file), I would be very grateful for any insight how to resolve this.

[LCM_seed_steipatr.zip](https://github.com/helske/seqHMM/files/2085588/LCM_seed_steipatr.zip)

**Comment by helske** [comment]
The default `fit_model` is not dependent on the seed, but the `build_lcm` is, as it generates the initial values randomly (emission matrix in this case). So it seems that with some initial values the optimization fails for some reason. Switching from EM algorithm to `nloptr` routines does not seem to help, but using log-space (argument `log_space = TRUE`) seems to work more often than not at least with 5 bins, although the optimization seems to be quite strongly dependent on the initial values (which is typical with EM algorithm).

**Comment by steipatr** [comment]
Thank you for this feedback. `log_space = TRUE` is certainly an improvement. It seems then that this issue is to be expected with the random emission matrix, therefore I am closing this.
