### ISSUE TITLE
Underlying algorithm (math derivation) or paper reference for build_mmm?

### ISSUE THREAD

**Issue by raylinz** [helske/seqHMM#32]
Which algorithm does build_mmm (building mixture Markov model) implement? Is there a paper or math derivation for reference? According to [this documentation section 2.3 on seqHMM](https://cran.r-project.org/web/packages/seqHMM/vignettes/seqHMM.pdf), it looks like the mixture hidden Markov models implemented by seqHMM is based on [the 1990 paper Mixed Markov Latent Class Models by van de Pol & Langeheine](https://www.jstor.org/stable/pdf/271087.pdf?seq=1#page_scan_tab_contents)? I didn't find the online free version of this paper though, so it's not clear to me about the math or algorithm details of what build_mmm does? 

Since the sequences that I'm trying to cluster are supposed to be independent from each other, and each sequence has different length. Hereby it would be necessary for me to know the underlying algorithm for build_mmm, such that I can decide if it's appropriate to call this function to solve my problem.

Thanks!

**Comment by helske** [comment]
The mixture Markov model in seqHMM is formulated as a hidden Markov model where the emission matrix has a diagonal form, i.e. each "hidden" state can only emit one type of observations, and the transition matrix has a block structure where each block corresponds to one mixture component (see page 7 in the vignette). So the underlying math follows "basic" HMM theory.

Based on your description of your data mixture Markov model should suit well for your problem. Sequences can have different lengths, you just have to pad the end of the series with NA values (which doesn't effect the likelihood).
