### ISSUE TITLE
plot.hmm: Is it possible to modify the arrow size based on the transition probability?

### ISSUE THREAD

**Issue by vrodriguezf** [helske/seqHMM#35]
Hi,

I am plotting a HMM that looks like this:

![image](https://user-images.githubusercontent.com/7083752/52472951-ecd44800-2b94-11e9-8dab-185bd68f7414.png)

As you can see, the arrow of the edge with the highest probability cannot be seen clearly, because of the width of the edge. I am setting `edge.arrow.size` to 1. I can fix this by setting `edge.arrow.size` to a higher value, but then the rest of the arrows are too big:

![image](https://user-images.githubusercontent.com/7083752/52473156-6704cc80-2b95-11e9-930e-e28120412d24.png)

I would like to modify the arrow size in terms of the transition probability, something like `edge.arrow.size = "auto"`. Is that possible?

Thanks!!

**Comment by satuhelske** [comment]
Hi, the plot is drawn using igraph and unfortunately it only allows for a fixed arrow size so there's nothing we can do in seqHMM to fix this.

There is a hack around it, but it requires you drawing multiple plots manually. Here's a link with the instructions for basic igraph: https://stackoverflow.com/questions/16942553/a-hack-to-allow-arrows-size-in-r-igraph-to-match-edge-width

You'd have to work with the plot.hmm function. Modifying the first plot outside of R is probably going to be an easier option than the hack though...

You can also set a fixed edge width, if you prefer that over large arrow heads.

**Comment by vrodriguezf** [comment]
Wow, thanks for that hack, I'll give it a try!
