### ISSUE TITLE
Feature request: allow prior state assignment probabilities from covariates

### ISSUE THREAD

**Issue by jamesross2** [helske/seqHMM#38]
Using covariates to create a prior cluster probability has been a powerful addition to my MHMMs. Is there any possibility to extend this functionality to prior state probability also? That way users could train models with informative starting state priors that vary with covariates, while still allowing for transitions between the states (allowing greater flexibility than the MHMM analogue).

**Comment by helske** [comment]
In principle yes, although there might be some identifiability issues if you try to estimate both prior cluster probabilities and prior state probabilities separately. It should be relatively straightforward modification to allow these, but it would need bit of coding nevertheless, and unfortunately at the moment we do not have resources to add new features to seqHMM. Pull requests are of course welcome.

**Comment by jamesross2** [comment]
Thanks for the response. Your point about identifiability issues for MHMMs with cluster priors is well taken, I should have been more clear that I was hoping for priors for the HMM objects only. I don't currently have the time resources to add new features either, so I'll close this for now. Thanks for the great package, @helske!
