### ISSUE TITLE
can you share data in csv format pls?

### ISSUE THREAD

**Issue by Sandy4321** [helske/seqHMM#43]
can you share data in csv format pls?

do you know more sources for categorical data time series?

**Comment by Sandy4321** [comment]
great news thanks
but I use python
is it possible to get data from this git hub repo?
where is data located? which folder?

**Comment by helske** [comment]
Data is in the data folder in R format, I don't know if there are tools to read them directly to Python, but as I said, you can read them in R and export them to csv from there.
