### ISSUE TITLE
how to find out optimal state numbers?

### ISSUE THREAD

**Issue by mark-jy** [helske/seqHMM#47]
this is another general question about hmm:

how to find out the most optimal numbers of states?

This's because I don't know how many states should be applied and must be inferred from data. Any references would be very much welcomed.

**Comment by helske** [comment]
This (and your earlier one) are good questions but not really suitable for these Github issues, which are intended for the package-specific issues such as bug reports. I suggest you ask these for example in [CrossValidated](https://stats.stackexchange.com/).

**Comment by mark-jy** [comment]
ok, thanks for the reminder
