### ISSUE TITLE
[Help request] How to test the model?

### ISSUE THREAD

**Issue by robdunne-uom** [helske/seqHMM#49]
I've used seqHMM to create a Markov Model from some sequence data using build_mm(). How do I then pass test data to it? Or get a list of transition probabilities for each state so I can do look ups? e.g if state1 then state2 is 0.4.

Is there a predict function in R, or something I'm missing in the library?

Thanks!

**Comment by helske** [comment]
Sorry, we missed this, as you hopefully noticed the transition matrices can be extracted for example with `model$transition`.  For testing, you could estimate your model with `fit_model` using partial data, and then use these estimated parameters for another model with the test data (without re-estimation).

There is no predict function for seqHMM models, although it would be pretty straightforward to implement that. Unfortunately at the moment, I do not have the resources to spare for that.

I'm closing this as old but feel free to open it again if needed.
