### ISSUE TITLE
HMM cluster assignments

### ISSUE THREAD

**Issue by loxavia** [helske/seqHMM#52]
Is there a method where one can get the probabilities of being in the clusters identified by HMM, I see this is available in the MHMM function but not in HMM. The only thing that I can see is the hidden paths.

**Comment by helske** [comment]
In MHMM, we have a mixture of multiple HMM's (soft "clusters"), but there is no concept of clusters for single HMM. You can get the probabilities of starting from certain hidden states by looking at the estimated initial probabilities (`model$initial_probs`) or individual-specific posterior probabilities of being in a certain state at a certain time `posterior_probs(model)`,

**Comment by loxavia** [comment]
Thank you very much, this is incredibly useful, been searching for these for a while.  Great work !
