### ISSUE TITLE
Apply to financial time series?

### ISSUE THREAD

**Issue by mackancurtaincheeks** [helske/seqHMM#54]
Is this applicable to financia time series data? If yes - how would somebody go about that?

**Comment by satuhelske** [comment]
This package is only applicable to the analysis of categorical time series. You can apply the methods to any data for which you think the assumptions are reasonable. You'll find information on the seqHMM package and the methods in the [article](http://dx.doi.org/10.18637/jss.v088.i03) as well as the seqHMM [vignettes](https://cran.r-project.org/web/packages/seqHMM/index.html).
