### ISSUE TITLE
Building a model with different sequence lengths

### ISSUE THREAD

**Issue by aaubry89** [helske/seqHMM#57]
Hi,

I am wondering if I can use this package for sequences which differ in their sequence lengths. I have sequences of mouse behavior and certain mice display more behaviors than others. I have read the vignette and don't see anything regarding this scenario. Any feedback would be really helpful. Thank you

**Comment by satuhelske** [comment]
Hi! I suppose you found your answer already, but the answer is yes. You should use the left = "DEL" option when creating the sequences with the seqdef function.
