### ISSUE TITLE
Parallel computation 

### ISSUE THREAD

**Issue by faezehMovahedi** [helske/seqHMM#59]
Hi
I wonder to run the fit_model function in parallel there is any extra step beside assigning the threads in the function? Could you please give an example of running the fit_model in parallel?

Thanks

**Comment by helske** [comment]
Yes, you only need the set the number of threads via `threads` argument. Note however that the parallelization with respect to the number of sequences, i.e. for a single sequence there's nothing to parallelise.

**Comment by faezehMovahedi** [comment]
Thanks!
