### ISSUE TITLE
Maximum number of colours in cpal/colorpalette

### ISSUE THREAD

**Issue by kyrantgs** [helske/seqHMM#62]
Firstly, a quick run down of the model that I am running:
I have 5911 individuals, 7 channels, the number of states in each channel is: mc_fit$model$n_symbols [1] 12 10 13  2  6 27  8, and there is a sequence length of 5660 for each person and channel (no difference in sequence lengths amongst individuals or channels). There are a total of 10764 distinct states in the data. I have run a cluster analysis using the OMSPELL algorithm to generate the dissimilarity measure, then created clusters using the partition around k-medoids algorithm, ultimately choosing the 11 cluster solution. I have completed hidden Markov models for each cluster to determine the best number of hidden states per cluster and to generate plausible parameter values for a mixture hidden Markov model. 

I am would to generate some basic plots for the HMMs but I am having some difficulties. 
The following command generates an error:
plot(mc_fit$model)
Error in seqHMM::colorpalette[[k]] : 
  attempt to select less than one element in get1index <real> 
If I manually set the cpal argument to cpal=1:10764 or cpal=colorpalette[[10764]][c(1:10764)] I get the same error.
I suspect the error occurs because there are insufficient colours in the default palette (the command seqHMM::colorpalette[[201]] returns Error in colorpalette[[201]] : subscript out of bounds). I have tried a number of other palettes/packages but it continues to generate the same error.
e.g.        plot(mc_fit$model, cpal=paletteer_c("grDevices::rainbow", 10764))
               Error in seqHMM::colorpalette[[k]] : 
               attempt to select less than one element in get1index <real>
Is there a workaround?

sessionInfo()
R version 4.1.3 (2022-03-10)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 18363)
other attached packages:
[1] seqHMM_1.2.1-1

**Comment by helske** [comment]
Thanks, the plot function itself does not use colorpalette, but it is used in `mc_to_sc` which transforms the multichannel model to single channel model. With more than 200 symbols, it tries to recycle the colors, but this doesn't actually work as intended. I'll fix that in a way that the user has to give their own palette in case the default palettes are not big enough.

**Comment by helske** [comment]
@kyrantgs Please let me know if this does not work and reopen the issue in that case, as I did not test this thoroughly.

**Comment by kyrantgs** [comment]
Tested, also not thoroughly, but works as expected in the cases that I used it for. The one small thing I would recommend is changing the error message to indicate that the new colour palette should be of length (number of observed states), just to make it clear that is what is needed for the self-defined palette.
