### ISSUE TITLE
Absorbing state broken in `build_mm()` (seqhmm 1.2.1-1)

### ISSUE THREAD

**Issue by ninohardt** [helske/seqHMM#65]
Here is a MWE:

```r
library(tidyverse)
library(seqHMM)

seqdata_raw<-
  rbind(1:4,
        c(2:4,NA),
        c(1,3,4,NA),
        c(3,2,1,4)) %>% data.frame %>% set_names(paste0('A',1:4)) %>% as_tibble


seqdata_seqdef<-seqdata_raw %>% TraMineR::seqdef() 

#here is the problem
seqdata_seqdef %>% seqHMM::build_mm()

#last line
#using 1.2.0:    4 0.000 0.000 0.000 0.000
#using 1.2.1-1:  4 0.250 0.250 0.250 0.250
```

Checking the last commit: https://github.com/helske/seqHMM/commit/c5cc92f7d1c40ad9a7078691fa8c42b1272499ff

 `transition_probs <- suppressMessages(TraMineR::seqtrate(observations))` has been replaced by `fit_model(build_hmm(` ...     and then `transition_probs <- model$transition_probs` ... in case there are missings (like unequal sequence lengths). So maybe that's where the issue is coming from.

**Comment by helske** [comment]
The result from 1.2.0 are clearly wrong as every row of the transition matrix should sum to one. The current results look correct to me, there are no transitions from state 4, and also no staying there, so the best guess is that the transition distribution is uniform. I think for absorbing state you should define the NA's in your example as 4? Then the last row of the transition matrix is (0,0,0,1).
