### ISSUE TITLE
not able to install the package

### ISSUE THREAD

**Issue by sapphire75710** [helske/seqHMM#8]
Hi there, 

I am trying to install the package on my macbook via Rstudio. Following the command, I got errors as following:

ld: warning: directory not found for option '-L/usr/local/lib/gcc/x86_64-apple-darwin13.0.0/4.8.2'
ld: library not found for -lgfortran
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [seqHMM.so] Error 1
ERROR: compilation failed for package ‘seqHMM’
* removing ‘/Library/Frameworks/R.framework/Versions/3.2/Resources/library/seqHMM’
Error: Command failed (1)

Any suggestion how I can solve it?

**Comment by helske** [comment]
I don't now much about Mac, but it seems that you are missing gfortran compiler on you macbook. 

I found potentially relevant issue on stackoverflow:
http://stackoverflow.com/questions/19758987/error-in-r-with-rcpp-and-rcpparmadillo-using-sourcecpp

And on Rcpp-devel:
http://lists.r-forge.r-project.org/pipermail/rcpp-devel/2014-February/007245.html

Here is more info: http://r.research.att.com/tools/

**Comment by sapphire75710** [comment]
Hi Jouni,

Thanks a lot for the reply! I've installed gfortran complier via http://r.research.att.com/tools/

This time I got error as following:
ld: warning: directory not found for option '-L/usr/local/lib/gcc/x86_64-apple-darwin13.0.0/4.8.2'
ld: library not found for -lquadmath
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [seqHMM.so] Error 1
ERROR: compilation failed for package ‘seqHMM’
* removing ‘/Library/Frameworks/R.framework/Versions/3.2/Resources/library/seqHMM’
Error: Command failed (1)

What do I miss this time?

**Comment by helske** [comment]
Bit of googling led me to this page: 
http://thecoatlessprofessor.com/programming/rcpp-rcpparmadillo-and-os-x-mavericks-lgfortran-and-lquadmath-error/

Hope that helps. Getting RcppArmadillo (which is used by seqHMM) to work with OS X seems to be a common problem.

**Comment by sapphire75710** [comment]
Hi Jouni,

Thanks a million! This time the package is successfully installed!

**Comment by helske** [comment]
Glad to hear everything works fine now. Let me know if there are some other problems in using the package.
